### ISSUE TITLE
"Your site may not work because theme / component Unformatted Code Detector has errors"

### ISSUE THREAD

**Issue by graham-mitchell-vcs** [lionel-rowe/unformatted_code_detector#16]
I am getting the following error on our Discourse site:

![image](https://user-images.githubusercontent.com/8654209/71038455-f7c51500-2175-11ea-88de-2b42444657bf.png)

Should the unformatted code detector be disabled, or is this a false alarm?

**Comment by dadoonet** [comment]
I'm getting the same message. Is there a way to know what the "errors" are?
Worth noting that the code detector does not detect in that case my code with the following text:

```
Trying again

{
"foo": "bar
}
```

**Comment by dadoonet** [comment]
Ping @lionel-rowe. Any chance you could look at this issue? Thanks!

**Comment by Germanicus1982** [comment]
Considering this has been an open issue for nearly a month now I'm going to consider this plugin dead and just deactivate.

**Comment by CoreElectronics** [comment]
Was such a *good* plugin

**Comment by robbiet480** [comment]
This just bit us over at the @homeassistant forums too. Almost 10 million visits a month, of which probably over half needed this plugin. Shame to see this go.

**Comment by GokulNC** [comment]
To everyone still facing the issue, just use the following repo till the above PR is merged by the author @lionel-rowe :
**https://github.com/gschlager/unformatted_code_detector**
